### ISSUE TITLE
React benchmark does not create/destroy table, but Angular benchmarks do

### ISSUE THREAD

**Issue by tbosch** [alincc/angular-test-table#3]
When repeatedly clicking on one of the 'Records' buttons, I can see that the Angular benchmarks destroy and create the table (a user can see that the table gets empty temporarily), which in the React benchmark I cannot see this.

This leads to skewed results when measuring clicking on the buttons multiple times, as React is just doing an incremental rendering, but Angular recreates the table anew. This shows especially for the 5000 rows dataset, where the rendering time itself (without scripting time) is about 2s in Angular, but in the React example it is almost nothing.

**Comment by alincc** [comment]
I updated the code for React and the tests seems more realistic.
